name: Build Windows (Tauri v2)

on:
  workflow_dispatch:
  push:
    branches: [ windows_build ]
  pull_request:
    branches: [ windows_build ]

jobs:
  build-windows:
    name: Build Tauri Windows Bundle
    runs-on: windows-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
      NEXT_TELEMETRY_DISABLED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node + cache
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Cache Next.js
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: nextjs-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nextjs-${{ runner.os }}-

      - name: Install frontend deps
        run: npm ci --prefer-offline --no-audit

      - name: Build Next.js
        run: npm run build

      # Rust (MSVC) + cache
      - name: Setup Rust (MSVC)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      # Cache pour PyInstaller build
      - name: Cache PyInstaller Build
        uses: actions/cache@v4
        with:
          path: |
            src-tauri/python-runtime
            ~/.cache/pip
          key: win-pyinstaller-v2-${{ runner.os }}-${{ hashFiles('src-tauri/python-runtime/requirements.txt', 'src-tauri/python-scripts/main.spec') }}
          restore-keys: |
            win-pyinstaller-v2-${{ runner.os }}-

      # Setup Python temporaire pour compilation
      - name: Setup Python for compilation
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # Compiler le code Python en executable avec corrections
      - name: Compile Python to executable (Fixed)
        shell: powershell
        run: |
          # Installer PyInstaller et dépendances avec versions spécifiques
          python -m pip install --upgrade pip
          
          # Utiliser PyInstaller 5.13.2 (version stable testée avec pandas/numpy)
          python -m pip install "pyinstaller==5.13.2"
          
          # Installer les dépendances Python
          python -m pip install -r src-tauri/python-runtime/requirements.txt
          
          # Afficher les versions pour debug
          python -c "import PyInstaller; print(f'[INFO] PyInstaller version: {PyInstaller.__version__}')"
          python -c "import pandas, numpy; print(f'[INFO] Pandas: {pandas.__version__}, NumPy: {numpy.__version__}')"
          
          # Créer le répertoire de destination
          New-Item -ItemType Directory -Force -Path "src-tauri\python-runtime" | Out-Null
          
          # Test rapide de l'import des modules critiques
          python -c "
          import secrets, hashlib, hmac, uuid, json, base64, io, os, sys
          import pandas as pd
          import numpy as np
          from openpyxl import Workbook
          print('[INFO] All critical modules import successfully')
          "
          
          # Compiler avec PyInstaller en utilisant le fichier spec corrigé
          cd src-tauri/python-scripts
          Write-Host "[INFO] Compiling with fixed spec file..."
          
          # Utiliser une compilation plus conservative avec tous les hooks
          python -m PyInstaller main.spec --clean --noconfirm --log-level INFO
          
          # Alternative de compilation si le spec échoue
          if (-Not (Test-Path "dist\data_processor.exe")) {
            Write-Host "[WARN] Spec compilation failed, trying direct approach..."
            python -m PyInstaller --onefile --console `
              --name data_processor `
              --hidden-import=secrets `
              --hidden-import=pandas._libs.tslibs.timedeltas `
              --hidden-import=pandas._libs.tslibs.np_datetime `
              --hidden-import=pandas._libs.tslibs.nattype `
              --hidden-import=numpy.random._common `
              --hidden-import=numpy.random.bit_generator `
              --hidden-import=numpy.random._pickle `
              --hidden-import=openpyxl.xml.functions `
              --collect-all pandas `
              --collect-all numpy `
              --collect-all openpyxl `
              main.py
          }
          
          # Vérifier que la compilation a réussi et déplacer l'executable
          if (Test-Path "dist\data_processor.exe") {
            Move-Item -Force "dist\data_processor.exe" "..\python-runtime\data_processor.exe"
            Write-Host "[OK] Executable moved successfully"
          } else {
            Write-Host "[ERROR] PyInstaller compilation failed - executable not found"
            Get-ChildItem "dist" -ErrorAction SilentlyContinue | ForEach-Object { Write-Host "Found in dist: $($_.Name)" }
            throw "PyInstaller compilation failed"
          }
          
          # Nettoyage des fichiers temporaires
          Remove-Item -Recurse -Force "build", "dist", "__pycache__" -ErrorAction SilentlyContinue

      # Test plus robuste de l'executable
      - name: Test compiled executable
        shell: powershell
        run: |
          $exe = "src-tauri\python-runtime\data_processor.exe"
          if (-Not (Test-Path $exe)) { 
            throw "Compiled executable not found" 
          }
          
          Write-Host "[OK] Executable compiled successfully: $exe"
          $sizeBytes = (Get-Item $exe).Length
          $sizeMB = $sizeBytes / 1MB
          $sizeRounded = [math]::Round($sizeMB, 2)
          Write-Host "[INFO] Executable size: $sizeRounded MB"
          
          # Test que l'executable se lance sans erreurs d'import
          try {
            $process = Start-Process -FilePath $exe -ArgumentList "TEST_LAUNCH" -Wait -PassThru -WindowStyle Hidden -RedirectStandardOutput "test_output.txt" -RedirectStandardError "test_error.txt"
            
            # Vérifier que le processus s'est lancé (peu importe le code de sortie)
            if ($process.HasExited) {
              Write-Host "[OK] Executable launches successfully (exit code: $($process.ExitCode))"
              
              # Afficher le contenu pour debug si nécessaire
              if (Test-Path "test_error.txt") {
                $errorContent = Get-Content "test_error.txt" -Raw -ErrorAction SilentlyContinue
                if ($errorContent -and $errorContent.Trim()) {
                  # Si l'erreur contient "ModuleNotFoundError", c'est un problème
                  if ($errorContent -match "ModuleNotFoundError") {
                    Write-Host "[ERROR] Module import error detected:"
                    Write-Host $errorContent
                    throw "Critical import error in executable"
                  } else {
                    Write-Host "[INFO] Non-critical error output: $errorContent"
                  }
                }
              }
              
              # Nettoyer les fichiers de test
              Remove-Item "test_output.txt", "test_error.txt" -ErrorAction SilentlyContinue
              
            } else {
              throw "Executable process did not complete"
            }
            
          } catch {
            Write-Host "[ERROR] Executable test failed: $_"
            # Afficher les logs d'erreur si disponibles
            if (Test-Path "test_error.txt") {
              $errorContent = Get-Content "test_error.txt" -Raw -ErrorAction SilentlyContinue
              if ($errorContent) {
                Write-Host "[ERROR] Error output: $errorContent"
              }
            }
            throw "Executable test failed: $_"
          }

      # Build avec l'action officielle Tauri
      - name: Build Tauri App (official action)
        uses: tauri-apps/tauri-action@v0
        
      # Exporter les artefacts
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-bundles
          path: src-tauri/target/release/bundle/**
