name: Build Windows (Tauri v2)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    name: Build Tauri Windows Bundle
    runs-on: windows-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
      NEXT_TELEMETRY_DISABLED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node + cache
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Cache Next.js
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: nextjs-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nextjs-${{ runner.os }}-

      - name: Install frontend deps
        run: npm ci --prefer-offline --no-audit

      - name: Build Next.js
        run: npm run build

      # Rust (MSVC) + cache
      - name: Setup Rust (MSVC)
        uses: dtolnay/rust-toolchain@stable

      - na
