name: Build Windows (Tauri v2)
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
      NEXT_TELEMETRY_DISABLED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Cache Next.js
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: nextjs-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: nextjs-${{ runner.os }}-

      - name: Install frontend deps
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Setup Rust (MSVC)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Create Python venv (Windows)
        shell: powershell
        run: |
          python -m venv src-tauri\python-runtime\venv
          & "src-tauri/python-runtime/venv/Scripts/pip.exe" install --upgrade pip
          & "src-tauri/python-runtime/venv/Scripts/pip.exe" install -r src-tauri/python-runtime/requirements.txt

      - name: Verify Python venv (Windows)
        shell: powershell
        run: |
          if (-Not (Test-Path "src-tauri/python-runtime/venv/Scripts/python.exe")) {
            throw "Python executable not found in venv/Scripts/"
          }
          & "src-tauri/python-runtime/venv/Scripts/python.exe" --version

      - name: Build Tauri bundle
        uses: tauri-apps/tauri-action@v0
        env:
          TAURI_PRIVATE_KEY: ""
          TAURI_KEY_PASSWORD: ""

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-bundles
          path: src-tauri/target/release/bundle/**
